INSERT INTO Action VALUES (3,'u',599,NULL);
INSERT INTO Action VALUES(6,'i',2990,NULL);
INSERT INTO Action VALUES(5,'d',NULL,NULL);
INSERT INTO Action VALUES(7,'u',1599,NULL);
INSERT INTO Action VALUES(1,'i',399,NULL);
INSERT INTO Action VALUES(9,'d',NULL , NULL);
INSERT INTO Action VALUES(10,'x',NULL,NULL);

INSERT INTO Temp VALUES(1, 1000); 
INSERT INTO Temp VALUES(2, 2000); 
INSERT INTO Temp VALUES(3, 500); 
INSERT INTO Temp VALUES(4, 6500); 
INSERT INTO Temp VALUES(5, 500); 